package auth

import (
	"testing"
)

func TestHashAndVerifyPassword(t *testing.T) {
	password := "12345678"

	// Hash the password
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	t.Logf("Generated hash: %s", hash)

	// Verify with correct password
	if !VerifyPassword(password, hash) {
		t.Fatal("VerifyPassword failed with correct password")
	}

	// Verify with wrong password
	if VerifyPassword("wrongpassword", hash) {
		t.Fatal("VerifyPassword succeeded with wrong password")
	}
}

func TestVerifyPasswordWithKnownHash(t *testing.T) {
	// Test with a known hash generated by the fixed code
	password := "12345678"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	t.Logf("Hash: %s", hash)

	if !VerifyPassword(password, hash) {
		t.Fatal("Verification failed for freshly hashed password")
	}
}

func TestVerifyPasswordInvalidHash(t *testing.T) {
	// Test with malformed hashes
	if VerifyPassword("password", "invalid") {
		t.Fatal("VerifyPassword succeeded with invalid hash format")
	}

	if VerifyPassword("password", "$argon2id$invalid") {
		t.Fatal("VerifyPassword succeeded with incomplete hash")
	}
}

func TestGenerateSecureToken_Length(t *testing.T) {
	// 32 bytes → 44 base64 URL-encoded chars (base64.URLEncoding.EncodeToString)
	token, err := GenerateSecureToken(32)
	if err != nil {
		t.Fatalf("GenerateSecureToken failed: %v", err)
	}

	if len(token) != 44 {
		t.Errorf("Expected token length 44, got %d", len(token))
	}
}

func TestGenerateSecureToken_Uniqueness(t *testing.T) {
	tokens := make(map[string]bool)
	for i := 0; i < 100; i++ {
		token, err := GenerateSecureToken(32)
		if err != nil {
			t.Fatalf("GenerateSecureToken failed: %v", err)
		}

		if tokens[token] {
			t.Errorf("Duplicate token generated at iteration %d", i)
		}
		tokens[token] = true
	}
}

func TestVerifyPassword_EmptyInputs(t *testing.T) {
	// Empty password
	if VerifyPassword("", "$argon2id$v=19$m=65536,t=1,p=8$c29tZXNhbHQ$abc123") {
		t.Fatal("VerifyPassword succeeded with empty password")
	}

	// Empty hash
	if VerifyPassword("password", "") {
		t.Fatal("VerifyPassword succeeded with empty hash")
	}

	// Both empty
	if VerifyPassword("", "") {
		t.Fatal("VerifyPassword succeeded with both empty")
	}
}
